[0m08:40:59.097100 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:40:59.097256 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:40:59.097432 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16687608595290623707_test_grants', identifier=None)"
[0m08:40:59.098819 [debug] [MainThread]: Using vertica connection "_test"
[0m08:40:59.098948 [debug] [MainThread]: On _test: BEGIN
[0m08:40:59.099043 [debug] [MainThread]: Opening a new connection, currently in state init
[0m08:40:59.099168 [debug] [MainThread]: vertica adapter: : COnnecting always
[0m08:40:59.176882 [debug] [MainThread]: vertica adapter: Got a retryable error when attempting to open a vertica connection.
1 attempts remaining. Retrying in 1 seconds.
Error:
Failed to establish a connection to the primary server or any backup address.
[0m08:41:00.178546 [debug] [MainThread]: vertica adapter: : COnnecting always
[0m08:41:00.222400 [debug] [MainThread]: vertica adapter: :P Error: Database Error
  Failed to establish a connection to the primary server or any backup address.
[0m08:41:00.222685 [debug] [MainThread]: On _test: No close available on handle
[0m08:41:00.222927 [debug] [MainThread]: vertica adapter: :P Error: Runtime Error
  Database Error
    Failed to establish a connection to the primary server or any backup address.
[0m08:41:00.442907 [debug] [MainThread]: Connection '_test' was properly closed.
