[0m08:34:51.945575 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:34:51.945760 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m08:34:51.945925 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16687604922821700227_test_grants', identifier=None)"
[0m08:34:51.947556 [debug] [MainThread]: Using vertica connection "_test"
[0m08:34:51.947713 [debug] [MainThread]: On _test: BEGIN
[0m08:34:51.947819 [debug] [MainThread]: Opening a new connection, currently in state init
[0m08:34:51.947936 [debug] [MainThread]: vertica adapter: : COnnecting always
[0m08:34:52.004737 [debug] [MainThread]: vertica adapter: Got a retryable error when attempting to open a vertica connection.
2 attempts remaining. Retrying in 1 seconds.
Error:
Failed to establish a connection to the primary server or any backup address.
[0m08:34:53.006289 [debug] [MainThread]: vertica adapter: : COnnecting always
[0m08:34:53.051648 [debug] [MainThread]: vertica adapter: Got a retryable error when attempting to open a vertica connection.
1 attempts remaining. Retrying in 1 seconds.
Error:
Failed to establish a connection to the primary server or any backup address.
[0m08:34:54.053093 [debug] [MainThread]: vertica adapter: : COnnecting always
[0m08:34:54.110572 [debug] [MainThread]: vertica adapter: :P Error: Database Error
  Failed to establish a connection to the primary server or any backup address.
[0m08:34:54.110974 [debug] [MainThread]: On _test: No close available on handle
[0m08:34:54.111603 [debug] [MainThread]: vertica adapter: :P Error: Runtime Error
  Database Error
    Failed to establish a connection to the primary server or any backup address.
[0m08:34:54.346508 [debug] [MainThread]: Connection '_test' was properly closed.
