[0m05:50:51.943485 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m05:50:51.943709 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m05:50:51.943899 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16687506522356889926_test_grants', identifier=None)"
[0m05:50:51.945463 [debug] [MainThread]: Using vertica connection "_test"
[0m05:50:51.945644 [debug] [MainThread]: On _test: BEGIN
[0m05:50:51.945752 [debug] [MainThread]: Opening a new connection, currently in state init
[0m05:50:51.946081 [debug] [MainThread]: vertica adapter: :P Error connecting to database: Failed to establish a connection to the primary server or any backup address.
[0m05:50:51.946283 [debug] [MainThread]: vertica adapter: :P Error: Database Error
  Failed to establish a connection to the primary server or any backup address.
[0m05:50:51.946401 [debug] [MainThread]: On _test: No close available on handle
[0m05:50:51.946588 [debug] [MainThread]: vertica adapter: :P Error: Runtime Error
  Database Error
    Failed to establish a connection to the primary server or any backup address.
[0m05:50:52.104369 [debug] [MainThread]: Connection '_test' was properly closed.
