[0m11:55:53.840339 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m11:55:53.840533 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m11:55:53.840764 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16657485540795241526_test_basic', identifier=None)"
[0m11:55:53.846130 [debug] [MainThread]: Using vertica connection "_test"
[0m11:55:53.846284 [debug] [MainThread]: On _test: BEGIN
[0m11:55:53.846393 [debug] [MainThread]: Opening a new connection, currently in state init
[0m11:58:04.457129 [debug] [MainThread]: vertica adapter: :P Error connecting to database: Failed to establish a connection to the primary server or any backup address.
[0m11:58:04.458039 [debug] [MainThread]: vertica adapter: :P Error: Database Error
  Failed to establish a connection to the primary server or any backup address.
[0m11:58:04.458465 [debug] [MainThread]: On _test: No close available on handle
[0m11:58:04.459102 [debug] [MainThread]: vertica adapter: :P Error: Runtime Error
  Database Error
    Failed to establish a connection to the primary server or any backup address.
[0m11:58:04.627104 [debug] [MainThread]: Connection '_test' was properly closed.
