[0m09:55:36.802910 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m09:55:36.803103 [debug] [MainThread]: Acquiring new vertica connection "_test"
[0m09:55:36.803275 [debug] [MainThread]: Creating schema "_ReferenceKey(database='vmart', schema='test16687653369440006892_test_any_value', identifier=None)"
[0m09:55:36.809820 [debug] [MainThread]: Using vertica connection "_test"
[0m09:55:36.810002 [debug] [MainThread]: On _test: BEGIN
[0m09:55:36.810118 [debug] [MainThread]: Opening a new connection, currently in state init
[0m09:55:36.810238 [debug] [MainThread]: vertica adapter: : COnnecting always
[0m09:55:36.855950 [debug] [MainThread]: vertica adapter: Got a retryable error when attempting to open a vertica connection.
1 attempts remaining. Retrying in 1 seconds.
Error:
Failed to establish a connection to the primary server or any backup address.
[0m09:55:37.857789 [debug] [MainThread]: vertica adapter: : COnnecting always
[0m09:55:37.930706 [debug] [MainThread]: vertica adapter: :P Error: Database Error
  Failed to establish a connection to the primary server or any backup address.
[0m09:55:37.931499 [debug] [MainThread]: On _test: No close available on handle
[0m09:55:37.932509 [debug] [MainThread]: vertica adapter: :P Error: Runtime Error
  Database Error
    Failed to establish a connection to the primary server or any backup address.
[0m09:55:38.164334 [debug] [MainThread]: Connection '_test' was properly closed.
